# Generated by Django 5.0.6 on 2024-07-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='animal',
            name='diet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.diettype'),
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.diettype')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.fooditem')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='medical_histories',
            field=models.ManyToManyField(related_name='animals', to='animals.medicalhistory'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.fooditem')),
            ],
        ),
    ]
