# Generated by Django 5.0.6 on 2024-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_diettype_medicalhistory_remove_animal_diet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='medical_histories',
        ),
    ]
