# Generated by Django 5.0.3 on 2024-07-04 16:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_medical_histories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('comande_needed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='animals.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='event_type',
             field=models.CharField(max_length=100, default='none'),
            preserve_default=False,
        ),
    ]
