# Generated by Django 5.0.3 on 2024-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_medicalstock_medicalhistory_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='comande_needed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
