# Generated by Django 4.2.13 on 2024-07-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_fooditem_comande_needed_fooditem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='schedule',
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
