# Generated by Django 4.2.13 on 2024-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_schedule_animal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalstock',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
