# Generated by Django 5.0.6 on 2024-07-15 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftimetable',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='stafftimetable',
            name='staff_id',
            field=models.ManyToManyField(related_name='timetables', to=settings.AUTH_USER_MODEL),
        ),
    ]
