# Generated by Django 4.2.13 on 2024-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_schedule_animal_location'),
        ('staff', '0002_remove_stafftimetable_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimetable',
            name='animals_id',
            field=models.ManyToManyField(blank=True, related_name='timetables', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='stafftimetable',
            name='task_type',
            field=models.CharField(choices=[('feeding', 'Feeding'), ('cleaning', 'Cleaning'), ('medication', 'Medication'), ('veterinary', 'Veterinary'), ('show', 'Show'), ('other', 'Other')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stafftimetable',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
